language: node_js
node_js:
  - "14"
sudo: false

cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: tfg-blockly-api
  on:
    branches: 
      only:
        - master