language: node_js
node_js:
  - "14"

sudo: false

script: 
  - npm start

branches:
  only:
  - Master
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: tfg-blockly-api
  on:
    branch: Master